/*
 * Copyright (c) Marley Arns
 * Licensed under the MIT License.
*/

#pragma once

#include <iomanip>
#include <cstdint>
#include <string>
#include <ostream>
#include <sstream>

#include "../Types/Address.hpp"
#include "../Types/MemoryRange.hpp"

namespace Azoth
{


/**
 * @brief Represents a loaded executable image or shared library in a process.
 *
 * A ProcessImage describes a contiguous memory range that corresponds to
 * a mapped binary image (e.g. executable or shared object), along with
 * its identifying metadata.
 *
 * @note This class is purely descriptive and does not imply ownership or lifetime
 * management of the underlying memory.
 */
class ProcessImage
{
public:
	/**
     * @brief Construct an invalid / empty process image.
     */
	ProcessImage() : baseAddress(0), size(0) {}

	/**
     * @brief Construct a process image with full metadata.
     *
     * @param baseAddr Base address where the image is mapped.
     * @param size     Size of the mapped image in bytes.
     * @param name     File name of the image (without path).
     * @param path     Full file system path of the image.
     */
	ProcessImage(Address baseAddr, size_t size, std::string name, std::string path)
		: baseAddress(baseAddr), size(size), name(std::move(name)), 
		path(std::move(path)) { }

	/**
     * @brief Construct a process image with full metadata.
     *
     * @param baseAddr Base address where the image is mapped.
     * @param size     Size of the mapped image in bytes.
     * @param path     Full file system path of the image.
	 * 
	 * The image name is then derived from the path by the implementation.
     */
	ProcessImage(Address baseAddr, size_t size, std::string path);

	Address baseAddress; ///< Base address of the image mapping
	size_t size;          ///< Size of the image in bytes
	std::string name;     ///< Image file name (without directory)
	std::string path;     ///< Full file system path to the image

	/**
     * @brief Check whether the image represents a valid mapping.
     *
     * @return True if baseAddress is non-zero and size is non-zero.
     */
	bool valid() const noexcept { return baseAddress && size; }

	/**
     * @brief Boolean conversion indicating validity.
     */
	explicit operator bool() const { return valid(); }



	/**
     * @brief Convert the image to its corresponding memory range.
	 * 
 	 * The returned range uses half-open interval semantics:
 	 * [baseAddress, baseAddress + size).
     */
	operator MemoryRange() const { return MemoryRange(baseAddress, baseAddress + size); };
};

/**
 * @brief Equality comparison for ProcessImage.
 * 
 * Returns true if both objects describe the same loaded binary.
 */
inline bool operator==(const ProcessImage& a, const ProcessImage& b)
{
     if (a.baseAddress != b.baseAddress || a.size != b.size)
          return false;
     return a.name == b.name && a.path == b.path;
}

/** @brief Writes a human-readable description of a ProcessImage to a stream. */
inline std::ostream& operator<<(std::ostream& os, const ProcessImage& img)
{
    if (!img.valid())
    {
        return os << "ProcessImage{ invalid }";
    }

    std::ios_base::fmtflags f(os.flags());
    const char oldFill = os.fill();

    os << "ProcessImage{ "
       << "baseAddress= " << img.baseAddress 
       << ", size=" << std::dec << img.size;

    if (!img.name.empty())
        os << ", name=\"" << img.name << "\"";

    if (!img.path.empty())
        os << ", path=\"" << img.path << "\"";

    os << " }";

    os.flags(f);
    os.fill(oldFill);
    return os;
}

/** @brief Returns a human-readable string representation of a ProcessImage. */
inline std::string to_string(const ProcessImage& img)
{
    std::ostringstream oss;
    oss << img;
    return oss.str();
}

/**
 * @brief Origin of a symbol within an image.
 */
enum class SymbolSource
{
    Export,  ///< Symbol originates from the module export table.
    Import,  ///< Symbol originates from the module import table.
    Internal ///< Symbol generated by analysis (not part of PE tables)
};

/**
 * @brief Represents a symbol associated with a loaded image.
 *
 * ImageSymbol describes a named address inside a module. Symbols may come
 * from different sources such as export tables, import tables, or analysis
 * results produced by the framework.
 *
 * Depending on the source, some fields may not be populated (e.g. forwarder
 * only applies to forwarded exports).
 */
class ImageSymbol
{
public:
     /// Constructs an invalid symbol.
	ImageSymbol() : address(0), index(0) {}

	ImageSymbol(Address addr, uint32_t idx, std::string name)
		: address(addr), index(idx), name(std::move(name)) {}

     /// Address of the symbol in the target process.
	Address address = 0;

     /// Index of the symbol in its originating table (export/import).
	uint32_t index = 0;

     /// Symbol name.
	std::string name;

     /// Name of the associated module (used primarily for imports).
     std::string modName;

     /// Forwarder target for forwarded exports (e.g. "KERNEL32.Sleep").
     std::string forwarder;

     /// Source from which this symbol was obtained.
     SymbolSource source = SymbolSource::Internal;

     /// Returns true if the symbol refers to a valid address.
	bool valid() const noexcept { return address; }
};


}